### ISSUE TITLE
What meanings of badge count on peer ？

### ISSUE THREAD

**Issue by sailingcai** [seanjameshan/blockchain#6]
Thanks for your demo.
I find there is a badge count on peer's image.
![2018-01-06_01-44-48](https://user-images.githubusercontent.com/102015/34621216-3e0ff454-f283-11e7-87d3-80521310ced6.png)
What does it mean?
Thx,

**Comment by seanjameshan** [comment]
It's message notification. If there are 10 messages, the count will be 10.
